<div class="clear"></div>

<div class="text_heading">
    <span class="head">Добавить группу разделов</span>
</div>

<div class="cont_text">

    <form action="/menu/addgroup/" method="post">
        <table>
            <tr>
                <td class="ttovar" width="200">Название</td>
                <td class="ttovar"><input name="data[title]" value="<?php echo $this->escape($this->menuGroup->title); ?>"/></td>
            </tr>
            <tr>
                <td class="ttovar">Обработчик</td>
                <td class="ttovar">
                    <select name="data[handler_id]">
                        <option value="">с подразделами</option>
                        <?php foreach ($this->handlerList as $handler): ?>
                        <option value="<?php echo $this->escape($handler->id); ?>"><?php echo $this->escape($handler->title); ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
        </table>
        <input id="save" name="save" type="submit" value="Сохранить"/>
    </form>

</div>