<h1><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Обращения<?php endif; ?></h1>

<div class="cont_text">

    <?php if (isset($this->exception_msg)): ?>
    <div>Ошибка: <?php echo $this->escape($this->exception_msg); ?></div>
    <br/>
    <?php endif; ?>

    <?php if ($this->isComplite == true): ?>
    <div>Сообщение принято. Вам на почту будет выслан ответ</div>
    <br/>
    <?php endif; ?>

    <form action="<?php echo $this->url(array('controller' => 'vote', 'action' => 'sendmsg')); ?>" method="post">
        <table>
            <tr>
                <td class="ttovar" width="150">ФИО</td>
                <td class="ttovar"><input name="data[fio]" value=""/></td>
            </tr>
            <tr>
                <td class="ttovar">Почтовый адрес</td>
                <td class="ttovar"><input name="data[address]" value=""/></td>
            </tr>
            <tr>
                <td class="ttovar">E-mail</td>
                <td class="ttovar"><input name="data[email]" value=""/></td>
            </tr>
            <tr>
                <td class="ttovar">Текст обращения</td>
                <td class="ttovar"><textarea name="data[short_text]"></textarea></td>
            </tr>
            <tr>
                <td class="ttovar" colspan="2"><input type="checkbox" name="data[accept]" onchange="checkAccept(this);" /> Я согласен</td>
            </tr>
        </table>
        <input id="save" name="save" type="submit" value="Отправить" disabled="disabled"/>
    </form>

</div>