<h1><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Документы<?php endif; ?></h1>

<div class="cont_text">

    <?php if (isset($this->exception_msg)): ?>
    <div>Ошибка: <?php echo $this->escape($this->exception_msg); ?></div>
    <br/>
    <?php endif; ?>

    <?php if (isset($this->breadcrumbs)): ?>
    <a href="<?php echo $this->url(array('controller' => 'document', 'action' => 'index', 'parent' => 0)); ?>">/..</a>
    <?php if (!empty($this->breadcrumbs)): ?>
        &nbsp;/
        <?php foreach ($this->breadcrumbs as $crumb): ?>
            <a href="<?php echo $this->url(array('controller' => 'document', 'action' => 'index', 'parent' => $crumb->id)); ?>"><?php echo $this->escape($crumb->title); ?></a>&nbsp;/
            <?php endforeach; ?>
        <?php endif; ?>
    <br/><br/>
    <?php endif; ?>

    <div class="sub-menu">
        <img src="/images/add.png"/>&nbsp;<a href="/document/addfolder/parent/<?php echo $this->escape($this->parentId); ?>/link/<?php echo $this->escape($this->link); ?>/">добавить папку</a>&nbsp;&nbsp;
        <img src="/images/add.png"/>&nbsp;<a href="/document/add/parent/<?php echo $this->escape($this->parentId); ?>/link/<?php echo $this->escape($this->link); ?>/">добавить документ</a>
    </div>

    <table width="100%">
        <tr>
            <td class="ttovar">Название</td>
            <td class="ttovar"></td>
        </tr>

        <?php if ($this->documentFolderList !== false): ?>
        <?php foreach ($this->documentFolderList as $item): ?>
            <tr>
                <td class="ttovar">
                    <img src="/images/folder.png"/>&nbsp;
                    <a href="<?php echo $this->url(array('controller' => 'document', 'action' => 'index', 'parent' => $item->id)); ?>"><?php echo $this->escape($item->title); ?></a></td>
                <td class="tedit">
                    <img src="/images/edit.png"/>&nbsp;<a href="/document/editfolder/id/<?php echo $item->id; ?>/parent/<?php echo $this->escape($this->parentId); ?>/link/<?php echo $this->escape($this->link); ?>/">редактировать</a><br/>
                    <img src="/images/delete.png"/>&nbsp;<a href="<?php echo $this->url(array('controller' => 'document', 'action' => 'deletefolder', 'id' => $item->id)) ?>" onclick="return confirmDelete('<?php echo $this->escape($item->title); ?>');" style="color: #830000">удалить</a></td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($this->documentList !== false): ?>
        <?php foreach ($this->documentList as $item): ?>
            <tr>
                <td class="ttovar"><img src="/images/document.png"/>&nbsp;<?php echo $this->escape($item->title); ?></td>
                <td class="tedit">
                    <img src="/images/edit.png"/>&nbsp;<a href="/document/edit/id/<?php echo $item->id; ?>/parent/<?php echo $this->escape($this->parentId); ?>/link/<?php echo $this->escape($this->link); ?>/">редактировать</a><br/>
                    <img src="/images/delete.png"/>&nbsp;<a href="<?php echo $this->url(array('controller' => 'document', 'action' => 'delete', 'id' => $item->id)) ?>" onclick="return confirmDelete('<?php echo $this->escape($item->title); ?>');" style="color: #830000">удалить</a></td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>

</div>