<h1><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Новости<?php endif; ?></h1>

<div class="cont_text">

    <?php if ($this->newsList !== false): ?>
    <div class="news">
        <?php foreach ($this->newsList as $item): ?>
        <div class="item">
            <div class="img">
                <?php if ($item->file->getName()): ?>
                <img src="/files<?php echo $this->escape($item->file->getSubPath()); ?>/<?php echo $this->escape($item->file->getPreview()); ?>"/>
                <?php endif; ?>
            </div>

            <div class="descript">
                <?php if ($this->linkInfo instanceof SM_Menu_Group): ?>
                <p class="title"><a href="<?php echo $this->url(array('controller' => 'news', 'action' => 'viewnews', 'id' => $item->id), $this->linkInfo->link . '-viewnews') ?>"><?php echo $this->escape($item->title); ?></a></p>
                <?php else: ?>
                <p class="title"><a href="<?php echo $this->url(array('controller' => 'news', 'action' => 'viewnews', 'id' => $item->id), $this->linkInfo->group->getLink() . '-' . $this->linkInfo->link . '-viewnews') ?>"><?php echo $this->escape($item->title); ?></a></p>
                <? endif; ?>
                <p class="date"><?php echo $this->escape(date('d.m.Y', strtotime($item->datePublic))); ?></p>

                <p><?php echo $this->escape($item->shortText); ?></p>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>

    <div class="clear"></div>
</div>