<div class="cont_text">
    <?php if ($this->authUserRole !== 'guest'): ?>

    <?php if (isset($this->exception_msg)): ?>
        <div>Ошибка: <?php echo $this->escape($this->exception_msg); ?></div>
        <br/>
        <?php endif; ?>

    <form action="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'title' => $this->contentPage->pageTitle)); ?>" method="post">

        <div><?php echo $this->ckeditor; ?></div>

        <input id="save" name="save" type="submit" value="Сохранить"/>
    </form>
    <br/>
    <?php else: ?>

    <?php echo $this->contentPage->content; ?>
    <?php endif; ?>

</div>