<div class="text_heading">
    <h1>Телефоны</h1>
</div>

<div class="cont_text">

    <?php if (isset($this->exception_msg)): ?>
    <div>Ошибка: <?php echo $this->escape($this->exception_msg); ?></div>
    <br/>
    <?php endif; ?>

    <form action="<?php echo $this->url(array('controller' => 'phone', 'action' => 'index')); ?>" method="post">
        <table>
            <tr>
                <td class="ttovar" width="170">Индекс</td>
                <td class="ttovar"><input name="data[post_index]" value="<?php echo $this->escape($this->phone->postIndex); ?>"/></td>
            </tr>
            <tr>
                <td class="ttovar">Адрес</td>
                <td class="ttovar"><input name="data[address]" value="<?php echo $this->escape($this->phone->address); ?>"/></td>
            </tr>
            <tr>
                <td class="ttovar">Телефон</td>
                <td class="ttovar"><input name="data[phone]" value="<?php echo $this->escape($this->phone->phone); ?>"/></td>
            </tr>


        </table>
        <input id="save" name="save" type="submit" value="Сохранить"/>
    </form>

</div>