
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />

        <style type="text/css">
            body { margin: 0; padding: 0; font-family: sans-serif, tahoma; }
        </style>

        <title><?php echo $this->escape($this->title) ?></title>

    </head>

    <body>

            <table style="width: 100%; height: 100%;" cellpadding="10" cellspacing="10" border="0">
                <tr>
                    <td valign="middle" align="center">
                        <form method="post" action="/login/" style="margin:0px; padding:0px;">

                            <table cellpadding="10" cellspacing="0" border="0" style="background-color: #373737; width: 300px; height: 100px;">

                                <tr>
                                    <td colspan="2" style="font-size:30px; color: #ffffff; padding-left: 25px; text-align: center;"><?php echo $this->escape($this->title) ?></td>
                                </tr>
                                <tr>
                                    <td style="color:white">Логин: </td>
                                    <td><input name="login" type="text" style="width:190px;border:10px;font-size: 16px;" /></td>
                                </tr>
                                <tr>
                                    <td style="color:white">Пароль:</td>
                                    <td><input name="psw" type="password" style="width:190px;border:10px;font-size: 16px;" /></td>
                                </tr>
                                <tr>
                                    <td>&nbsp;</td>
                                    <td><input type="submit" value="Войти" style="width:190px;font-size: 16px;"/></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td><?php if (isset($this->login_fail)): ?><div style="color:white; font-weight:bold; font-size:12px;"><?php echo $this->result->loginFailed ?></div><?php endif; ?></td>
                                </tr>


                            </table>
                        </form>

                    </td>
                </tr>
            </table>

    </body>
</html>