
<div class="text_heading">
    <span class="head">Редактировать площадку</span>
</div>

<div class="cont_text">

    <?php if (isset($this->exception_msg)): ?>
    <div>Ошибка: <?php echo $this->escape($this->exception_msg); ?></div>
    <br/>
    <?php endif; ?>

    <form action="<?php echo $this->url(array('controller' => 'banner', 'action' => 'editPlace', 'id' => $this->place->id)); ?>" method="post" enctype="multipart/form-data">
        <table width="100%">
            <tr>
                <td class="ttovar_title">Название</td>
                <td class="ttovar"><input name="data[title]" value="<?php echo $this->escape($this->place->title); ?>"/></td>
            </tr>
            <tr>
                <td class="ttovar_title">Ширина</td>
                <td class="ttovar"><input name="data[width]" value="<?php echo $this->escape($this->place->width); ?>"/></td>
            </tr>
            <tr>
                <td class="ttovar_title">Высота</td>
                <td class="ttovar"><input name="data[height]" value="<?php echo $this->escape($this->place->height); ?>"/></td>
            </tr>
            <tr>
                <td class="ttovar_title">Время между сменой баннеров</td>
                <td class="ttovar"><input name="data[change_time]" value="<?php echo $this->escape($this->place->changeTime); ?>"/></td>
            </tr>
        </table>
        <input id="save" name="save" type="submit" value="Сохранить"/>
    </form>

</div>