<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    <title>Официальный сайт администрации поселка Старопестерево</title>

    <link rel="stylesheet" type="text/css" href="/css/jquery-ui.css"/>
    <link rel="stylesheet" type="text/css" href="/css/styles-special.css"/>

    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/i18n/jquery.ui.datepicker-ru.js"></script>

    <script type="text/javascript" src="/js/scripts.js"></script>

    <!--[if lte IE 6]>
    <script src="/js/png.js"></script>
    <script>DD_belatedPNG.fix('div, a, img, span');</script>
    <![endif]-->
    <!--[if !IE 7]>
    <style type="text/css">
        #wrap {
            display: table;
            height: 100%
        }
    </style>
    <![endif]-->

</head>
<body class="<?= $this->escape($this->currentSiteFontSize); ?> <?= $this->escape($this->currentSiteColor); ?>">

<div class="site-mode-panel">
    <div class="site-color-change">Цвет сайта:
        <a href="#" class="white">A</a>
        <a href="#" class="black">A</a>
    </div>

    <div class="site-font-resize">Размер шрифта:
        <a href="#" class="small">A</a>
        <a href="#" class="medium">A</a>
        <a href="#" class="large">A</a>
    </div>

    <div class="site-mode-change">
        <a href="/index/change-mode/mode/<?= $this->currentSiteMode == 'normal' ? 'special' : 'normal'; ?>"><?= $this->currentSiteMode == 'normal' ? 'Версия для слабовидящих' : 'Обычная версия'; ?></a>
    </div>
</div>

<div id="center">
    <div class="sidebar">
        <div id="mainmenu-static">
            <ul class="menu">
                <?php foreach ($this->menuList as $group): ?>
                    <li>
                        <?php if ($group->getHandler() !== null): ?>
                            <a href="<?= $this->escape($group->getUrl($this->authUserRole)); ?>" <?php if ($this->menuActiveGroup !== false && $this->menuActiveGroup->link == $group->link): ?>
                                class="selected"
                            <?php endif; ?> title="<?= $this->escape($group->title); ?>"><?= $this->escape($group->title); ?></a>
                        <?php else: ?>
                            <a href="#" <?php if ($this->menuActiveGroup !== false && $this->menuActiveGroup->link == $group->link): ?>
                                class="selected"
                            <?php endif; ?> title="<?= $this->escape($group->title); ?>"><?= $this->escape($group->title); ?></a>
                        <?php endif; ?>
                        
                        <?php $itemList = $group->getItemList();
                        if ($itemList !== false): ?>
                            <ul>
                                <?php foreach ($itemList as $item): ?>
                                    <?php if ($item->isVisible): ?>
                                        <li><a href="<?= $this->escape($item->getUrl($this->authUserRole)); ?>" class="selected" title="<?= $this->escape($item->title); ?>"><?= $this->escape($item->title); ?></a></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>

                    </li>
                <?php endforeach; ?>

                <?php if ($this->authUserRole !== 'guest'): ?>
                    <li>
                        <a href="/menu/">Управление разделами</a>

                        <div class="round_bottom_left"></div>
                        <div class="round_bottom_right"></div>
                        <div class="round_top_left"></div>
                        <div class="round_top_right"></div>
                    </li>
                    <li>
                        <a href="/banner/">Баннеры</a>

                        <div class="round_bottom_left"></div>
                        <div class="round_bottom_right"></div>
                        <div class="round_top_left"></div>
                        <div class="round_top_right"></div>
                    </li>
                    <li>
                        <a href="/phone/">Телефоны</a>

                        <div class="round_bottom_left"></div>
                        <div class="round_bottom_right"></div>
                        <div class="round_top_left"></div>
                        <div class="round_top_right"></div>
                    </li>
                <?php endif; ?>
            </ul>

            <?php if ($this->authUserRole !== 'guest'): ?>
                <div>
                    <?= $this->authUser; ?> <a href="/login/logout/">(выход)</a>
                </div>
            <?php endif; ?>

        </div>
    </div>

    <div class="content">
        <div class="content_header">
            <div class="site-name">
                <a href="/" class="big">Старопестерево</a>
                <p>Официальный сайт администрации<br/>Старопестеревского сельского поселения.</p>
            </div>
            
            <div class="posel">Сельские поселения Беловского района:</div>

            <div class="header_img">
                <div class="search">
                    <form action="/search/index/" method="post">
                        <input type="text" name="query" class="search_field" value=""/>
                        <input type="submit" name="submit_search" class="search_button" value="ПОИСК"/>
                    </form>

                </div>
            </div>

        </div>

        <div class="content_center">
            <?php if ($this->pathway && $this->linkInfo->link != 'main_page'): ?>
                <div class="pathway">
                    <a href="/" class="home"></a>
                    <? foreach ($this->pathway as $pathway): ?>
                        <?= $this->escape($pathway['title']); ?> <span class="separator">>></span>
                    <?php endforeach; ?>
                    <?= $this->escape($this->linkInfo->title); ?>
                </div>
            <?php endif; ?>

            <?= $this->layout()->content; ?>


        </div>
        <div class="clear"></div>

        <?php if (is_object($this->linkInfo) && $this->linkInfo->link == 'main_page'): ?>
            <div class="zakon">
                <div class="text_heading">
                    <h1>Законодательство</h1>
                </div>

                <?php if ($this->documentList !== false): ?>
                    <?php foreach ($this->documentList as $item): ?>
                        <div class="item">
                            <p class="date"><?= $this->escape(date('d.m.Y', strtotime($item->dateCreate))); ?></p>

                            <p class="description">
                                <?php if (is_object($item->parent)): ?>
                                    <a href="<?= $this->url(array('controller' => 'document', 'action' => 'viewdoc', 'id' => $item->id, 'parent' => $item->parent->id), $item->link->group->getLink() . '-' . $item->link->link . '-viewdoc') ?>" title="<?= $this->escape($item->title); ?>"><?= $this->escape($item->title); ?></a>
                                <?php else: ?>
                                    <a href="<?= $this->url(array('controller' => 'document', 'action' => 'viewdoc', 'id' => $item->id, 'parent' => '0'), $item->link->group->getLink() . '-' . $item->link->link . '-viewdoc') ?>" title="<?= $this->escape($item->title); ?>"><?= $this->escape($item->title); ?></a>
                                <?php endif; ?>
                            </p>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>

                <!--
                <div class="pages">
                    <span>1</span> <a href="/">2</a> <a href="/">3</a> ...
                </div>
                -->

                <div class="zakon_shadow"></div>
            </div>
        <?php endif; ?>

    </div>

</div>

<div class="pad"></div>
<div id="footer">
    <div class="footer_center">

        <div class="contacts">
            <p>+7 <?= $this->escape($this->mainPhone->phone); ?> <?= $this->escape($this->mainPhone->postIndex); ?>  <?= $this->escape($this->mainPhone->address); ?></p>
        </div>
        <div class="made">
            <a href="/">inVoice Group</a>

            <!-- Yandex.Metrika informer -->
            <a href="https://metrika.yandex.ru/stat/?id=44427715&amp;from=informer"
               target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/44427715/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
                                                   style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" class="ym-advanced-informer" data-cid="44427715" data-lang="ru" /></a>
            <!-- /Yandex.Metrika informer -->

            <!-- Yandex.Metrika counter -->
            <script type="text/javascript">
                (function (d, w, c) {
                    (w[c] = w[c] || []).push(function() {
                        try {
                            w.yaCounter44427715 = new Ya.Metrika({
                                id:44427715,
                                clickmap:true,
                                trackLinks:true,
                                accurateTrackBounce:true
                            });
                        } catch(e) { }
                    });

                    var n = d.getElementsByTagName("script")[0],
                        s = d.createElement("script"),
                        f = function () { n.parentNode.insertBefore(s, n); };
                    s.type = "text/javascript";
                    s.async = true;
                    s.src = "https://mc.yandex.ru/metrika/watch.js";

                    if (w.opera == "[object Opera]") {
                        d.addEventListener("DOMContentLoaded", f, false);
                    } else { f(); }
                })(document, window, "yandex_metrika_callbacks");
            </script>
            <noscript><div><img src="https://mc.yandex.ru/watch/44427715" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
            <!-- /Yandex.Metrika counter -->
        </div>
    </div>
</div>

</body>
</html>








