<div class="content_center_left">
    <div class="text_heading">
        <h1>О нас</h1>
    </div>

    <div class="cont_text">
        <?= $this->contentPage->content; ?>
    </div>
</div>

<div class="content_center_right">
    <div class="news">
        <h2>Новости</h2>

        <?php if ($this->newsList !== false): ?>
            <?php foreach ($this->newsList as $item): ?>
                <div class="item">
                    <p class="date"><?= $this->escape(date('d.m.Y', strtotime($item->datePublic))); ?></p>

                    <p><a href="<?= $this->url(array('controller' => 'news', 'action' => 'viewnews', 'id' => $item->id), $this->linkInfoNews->link . '-viewnews') ?>" title="<?= $this->escape($item->title); ?>"><?= $this->escape($item->title); ?></a></p>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>